import React, { useState, useCallback, useEffect } from "react";
import { TwitterShareButton } from "react-share";
import { TwitterIcon } from "react-share";
import { Tweet } from "@/lib/types";
import { useRequestCallback } from "@/lib/api";

interface Props {
  tweet: Tweet
}

const HeartIcon = ({ filled, color }: { filled: boolean, color: string }) => {
  return (
    <div className={`text-[${color}] text-sm  flex items-center space-x-2 bg-transparent  hover:bg-slate-100 rounded-3xl hover:bg-opacity-10 p-2 hover:text-sky-400`}>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" strokeWidth={1.5} stroke={color} fill={filled ? color : "none"} className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
      </svg>
    </div>
  )
};

const Tweet = ({ tweet }: Props) => {
  const { id, author, content, likes, likedByUser } = tweet;
  const [liked, setLiked] = useState(likedByUser);
  const likeTweet = useRequestCallback(`/like/${id}`);

  const handleToggleLike = useCallback(() => {
    // Optimistic update before we receive ground truth from backend.
    setLiked((curr) => !curr);
    if (!liked) {
      likeTweet();
    }
  }, [liked, likeTweet]);

  useEffect(() => {
    setLiked(tweet.likedByUser);
  }, [tweet]);

  const color = liked ? "#F91880" : "#71767B";

  return (
    <div className='p-4 cursor-pointer border-b border-zinc-700 hover:bg-gray-600 hover:bg-opacity-30 w-full align-center'>
      <div className='flex flex-row items-center justify-between space-x-3'>
        <div className='flex flex-col'>
          <p className='text-xs sm:text-sm font-light hover:underline pb-2'>
            <b>{author.handle}</b>
          </p>
          <p className='text-sm whitespace-pre-line'>{content}</p>
        </div>
        <div className='flex flex-row'>
          <div className='flex items-center justify-between mt-1' onClick={handleToggleLike}>
            <HeartIcon color={color} filled={liked} />
          </div>
          <div className='flex items-center justify-between mt-1'>
            <TwitterShareButton url="https://gptwitter-neon.vercel.app/" title={content + "\n\nThis tweet was generated by an AI with GPTwitter @GPTweet4"}> 
              <TwitterIcon round size={30} />
            </TwitterShareButton>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Tweet;
